### PR TITLE
define("buster") and preloadSources/preloadTests

### PR DESCRIPTION
**Pull request by dominykas**
Patches for https://github.com/busterjs/buster/issues/223 and https://github.com/busterjs/buster/issues/224

While at it, also using buster as a module in the require() call

### CODE REVIEW

**Comment by flosse** [comment]
+1

**Comment by cjohansen** [comment]
I'm confused - didn't we already pull this? Into @johlrogge's repo, which was then moved here?

**Comment by johlrogge** [comment]
I share your confusion... I have been a bit offline regaring buster-amd but seems we need to get to the bottom of this new root-repo-thingy...

**Comment by johlrogge** [comment]
It seems my repo was not moved, buster-js became the new root... should I apply the patch? It looks like it would apply cleanly and is needed?

**Comment by cjohansen** [comment]
In that case - sure, go ahead :)

**Pull request merged**
